### ISSUE TITLE
Problem in boolean[][] computeCheckRestrictions(Piece threat)

### ISSUE THREAD

**Issue by Cyention** [informatikprojekt-q11-2/repository_name#4]
Bei Ausführen der `test2()` Methode in `Test_SearchPieces` tritt folgendes Problem auf:
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 8
	at supertolles.schachspiel.GameLogic.computeCheckRestrictions(GameLogic.java:471)
	at supertolles.schachspiel.GameLogic.computeMoveOptions(GameLogic.java:399)
	at supertolles.schachspiel.GameLogic.isCheckMate(GameLogic.java:119)
	at supertolles.schachspiel.test.Test_SearchPieces.test2(Test_SearchPieces.java:69)
	at supertolles.schachspiel.test.Test_SearchPieces.<init>(Test_SearchPieces.java:29)
	at supertolles.schachspiel.main.main(main.java:24)`

@alxhab ich denke, du musst nur die `boolean isInBounds(int x, int y)` Methode einfügen

**Comment by alxhab** [comment]
gute und schlechte Nachricht.
Ich habe den Fehler gefixt.
Jetzt schmeist die Methode den Fehler:
    NullpoiterException
        at supertolles.schachspiel.GameLogic.**searchStraights**(GameLogic.java:281)
	at supertolles.schachspiel.GameLogic.searchThreatFigure(GameLogic.java:175)
	at supertolles.schachspiel.GameLogic.isCheck(GameLogic.java:140)
	at supertolles.schachspiel.GameLogic.computeKingMovement(GameLogic.java:650)
	at supertolles.schachspiel.GameLogic.computeMoveOptions(GameLogic.java:451)
	at supertolles.schachspiel.GameLogic.isCheckMate(GameLogic.java:119)
	at supertolles.schachspiel.test.Test_SearchPieces.test2(Test_SearchPieces.java:69)
	at supertolles.schachspiel.test.Test_SearchPieces.<init>(Test_SearchPieces.java:29)
	at supertolles.schachspiel.main.main(main.java:24)
